#!/bin/sh

#Autostart
picom -b &
killall sxhkd; sxhkd &
killall dunst; dunst &
feh --bg-fill -r -z $HOME/.walls &
xsetroot -cursor_name left_ptr &
redshift &
unclutter &
xss-lock -- i3lock -i $HOME/.Xresources.d/lock.png &
clipmenud &
mpd &
mpdscribble &
sleep 5 && $HOME/.config/polybar/launch.sh &
$HOME/.todo/todo-conky
$HOME/.dropbox-dist/dropboxd &

#variable
alias bc='bspc config'
alias br='bspc rule'

#Workspaces
bspc monitor -d 1 2 3 4 5 6 7

#Others
bc border_width 0
bc window_gap 10
bc split_ratio 0.50
bc borderless_monocle true
bc gapless_monocle false
bc focus_follows_pointer true

#rules
br -a feh state=floating
br -a sxiv state=floating
br -a mpv state=floating
br -a Viewnior state=floating
