# Shell variables
# Generated by 'wal'
wallpaper='/home/ajibola/.wallpapers/papers.co-ma96-anno-tree-nature-2560x1600.jpg'

# Special
background='#212B3C'
foreground='#C1D3E5'
cursor='#C1D3E5'

# Colors
color0='#212B3C'
color1='#89A6B9'
color2='#9EB8CC'
color3='#9CC2D6'
color4='#AEC5DB'
color5='#B7CCE2'
color6='#BBD1E4'
color7='#C1D3E5'
color8='#757575'
color9='#89A6B9'
color10='#9EB8CC'
color11='#9CC2D6'
color12='#AEC5DB'
color13='#B7CCE2'
color14='#BBD1E4'
color15='#C1D3E5'
