# Shell variables
# Generated by 'wal'
wallpaper='/home/ajibola/.Xresources.d/wall_images/b24q8oe.jpg'

# Special
background='#272e38'
foreground='#C9BEB4'
cursor='#C9BEB4'

# Colors
color0='#272e38'
color1='#698898'
color2='#5290A5'
color3='#6F99A9'
color4='#8B9CA5'
color5='#93A5AD'
color6='#A2A1A0'
color7='#C9BEB4'
color8='#7d8187'
color9='#698898'
color10='#5290A5'
color11='#6F99A9'
color12='#8B9CA5'
color13='#93A5AD'
color14='#A2A1A0'
color15='#C9BEB4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
